---
- name: Install required packages
  yum:
    name:
      - gcc
      - make
      - kernel-headers
      - kernel-devel
      - perl
      - wget
      - open-vm-tools
    state: present

- name: Create vagrant user
  user:
    name: "{{ bootstrap_vagrant_user }}"
    create_home: true
    groups:
      - wheel
    shell: /bin/bash
    append: true
    state: present

- name: Add vagrant user public key
  authorized_key:
    user: "{{ bootstrap_vagrant_user }}"
    key: "{{ bootstrap_vagrant_user_ssh_public_key }}"
    manage_dir: true
    comment: ansible
    exclusive: true
    state: present
  when: bootstrap_vagrant_user_ssh_public_key | length > 0
  become: true

- name: Add vagrant user to sudo
  lineinfile:
    path: "/etc/sudoers.d/{{ bootstrap_vagrant_user }}"
    line: "{{ bootstrap_vagrant_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: true
    validate: "visudo -cf %s"
  when: bootstrap_vagrant_allow_password_less_sudo | bool
  become: true

- name: Set includedir in sudoers
  lineinfile:
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  when: bootstrap_vagrant_allow_password_less_sudo | bool
  become: true

- name: Check ssh config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PubkeyAuthentication yes"
    state: present
  notify: "Restart sshd"
  become: true

- name: Allow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication  yes"
  notify: "Restart sshd"
  become: true

- name: Find ssh host keys
  find:
    paths: /etc/ssh/
    patterns: "*key*"
  register: host_keys_to_delete

- name: Delete ssh host keys
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ host_keys_to_delete.files }}"
