---
- name: install required packages
  yum:
    name:
      - gcc
      - make
      - kernel-headers
      - kernel-devel
      - perl
      - wget
      - open-vm-tools
    state: present
    autoclean: yes


- name: find ssh host keys
  find:
    paths: /etc/ssh/
    patterns: "*key*"
  register: host_keys_to_delete

- name: delete ssh host keys
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ host_keys_to_delete.files }}"
